baseURL = "http://phd.carloscamara.es"
languageCode = "en-US"
defaultContentLanguage = "es"

title = "Comunes urbanos: Lecciones desde la Barcelona de principios del siglo XXI"
theme = "learn"
#themesdir = "../.."
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= true

[params]
  editURL = "https://github.com/ccamara/phd-hugo/edit/master/content/"
  description = "Tesis doctoral"
  author = "Carlos Cámara-Menoyo"
  showVisitedLinks = true
  # Change default color scheme with a variant one. Can be "red", "blue", "green".
  themeVariant = "orange"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[Languages]

[Languages.es]
title = "Comunes urbanos: Lecciones desde la Barcelona de principios del siglo XXI"
weight = 1
languageName = "Spanish"

[[Languages.es.menu.shortcuts]]
name = "<i class='fa fa-fw fa-bookmark'></i> Sobre esta edición"
identifier = "about"
url = "/about"
weight = 0

[[Languages.es.menu.shortcuts]]
name = "<i class='fa fa-fw fa-user-circle'></i> Sobre el autor"
identifier = "author"
url = "https://carloscamara.es"
weight = 1

[[Languages.es.menu.shortcuts]]
name = "<i class='fa fa-fw fa-github'></i> Github repo"
identifier = "ds"
url = "https://github.com/ccamara/phd-hugo"
weight = 10

[Languages.en]
title = "Documentation for Hugo Learn Theme"
weight = 1
languageName = "English"
